### ISSUE TITLE
Add Delay between requests in folder

### ISSUE THREAD

**Issue by caringco** [LunaticoCR/insomnia-plugin-run-folder#2]
Thanks for this plugin. Is it possible to add a delay between requests sent in the same folder?
We run into an issue where we set a parameter with current unixtime and the parameter value needs to be unique. When we do send requests - as the requests run simultaneously - some of the requests fail.

**Comment by LunaticoCR** [comment]
It should be possible. But it is my understanding that requests don't run simultaneously, they run sequentially, one after the other. I have several folders where the results of one request are needed for the next one and never had a failure.

**Comment by caringco** [comment]
Thanks for your quick reply.

To test use the below curl code. The time stamp being used is the function Timestamp -> Unix - duplicate these requests in a folder - say 10 requests and run it. You will note that the time stamp observed is duplicated in some requests.

I am using a public requestbin: https://requestbin.com/r/en27f8onkqnnj/1miJ5td8xPs9qqsCh2usswoOkJC

curl --request POST \
  --url https://en27f8onkqnnj.x.pipedream.net/ \
  --header 'Content-Type: application/json' \
  --data '{
	"TimeStamp": "{% now 'unix', '' %}"
}'

**Comment by LunaticoCR** [comment]
So I've done some testing with your example, and I was able to reproduce what you saw when using timestamp in unix format. However when I changed the timestamp to be milliseconds then I didn't see any repeated numbers. This to me suggests that Insomnia is most likely not doing requests in parallel. As I mentioned previously, I have folders where one request depends on  results from the previous one and I've never seen a failure because a request tries to run before the results from the previous one are ready.

Will using Timestamp -> Milliseconds resolve your issue?

**Comment by caringco** [comment]
Thanks for taking the time to test this. However we require a unique unix timestamp in our requests. Would appreciate if you were able to help fix?

**Comment by LunaticoCR** [comment]
Adding a delay between requests on this plugin is very simple, but I am not convinced this is the right solution. If your system needs a guarantee that each request needs a unique unix timestamp then I would say the design of that endpoint is wrong and you should probably reevaluate that. The only way to guarantee that you get unique unix timestamps will be by adding a delay of 1 second between requests, and that's too much of a delay, a folder with 10 requests with a latency of 10ms each will normally take 100ms, with the proposed delay it would take over 10 seconds.  Unix timestamp is seconds since epoch, there's no way to guarantee that two requests won't happen within the same second. You could change your system to use a timestamp in milliseconds, although there's still a slim chance of getting two requests within the same millisecond. If you need absolute uniqueness I would suggest to use timeuuids ( [UUIDv1](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_(date-time_and_MAC_address) ).
If you really want to go ahead with a delay between requests then I would suggest you modify the plugin locally and add a delay there. The file you would need to modify is at ```~/Library/Application\ Support/Insomnia/plugins/insomnia-plugin-run-folder/run-folder.js``` (macOS path, YMMV on other operating systems). Just add your delay in the for-loop that does the requests, save and reload plugins in your Insomnia preferences.
